# Docker aliases
abbr -a dbu 'docker build'
abbr -a dkb 'docker build'
abbr -a dkc 'docker compose'
abbr -a dexec 'docker exec'
abbr -a dke 'docker exec'
abbr -a di 'docker images'
abbr -a dki 'docker images'
abbr -a dlog 'docker logs'
abbr -a dkl 'docker logs'
abbr -a dps 'docker ps'
abbr -a dkp 'docker ps'
abbr -a dkpa 'docker ps -a'
abbr -a dkr 'docker run'
abbr -a drm 'docker rm'
abbr -a dkrm 'docker rm'
abbr -a drmi 'docker rmi'
abbr -a dkrmi 'docker rmi'
abbr -a dks 'docker start'
abbr -a dkt 'docker stop'
abbr -a dvls 'docker volume ls'
abbr -a dkx 'docker exec -it'
abbr -a dkps 'docker ps'

# Docker Compose aliases
abbr -a dkcr 'docker compose run'
abbr -a dcup 'docker compose up'
abbr -a dcupd 'docker compose up -d'
abbr -a dcdown 'docker compose down'
abbr -a dclogs 'docker compose logs'
abbr -a dcps 'docker compose ps'
abbr -a dcbuild 'docker compose build'
abbr -a dcrestart 'docker compose restart'
abbr -a dkcps 'docker compose ps'
