GOOSE_MODEL: gpt-5
OPENAI_BASE_PATH: v1/chat/completions
OPENAI_HOST: https://api.openai.com
extensions:
  atlassian:
    args:
    - -y
    - mcp-remote
    - https://mcp.atlassian.com/v1/sse
    available_tools: []
    bundled: null
    cmd: npx
    description: null
    enabled: false
    env_keys: []
    envs: {}
    name: atlassian
    timeout: 300
    type: stdio
  autovisualiser:
    available_tools: []
    bundled: true
    description: null
    display_name: Auto Visualiser
    enabled: false
    name: autovisualiser
    timeout: 300
    type: builtin
  computercontroller:
    available_tools: []
    bundled: true
    description: null
    display_name: Computer Controller
    enabled: false
    name: computercontroller
    timeout: 300
    type: builtin
  context7:
    args:
    - -y
    - '@upstash/context7-mcp'
    available_tools: []
    bundled: null
    cmd: npx
    description: null
    enabled: false
    env_keys: []
    envs: {}
    name: context7
    timeout: 300
    type: stdio
  developer:
    available_tools: []
    bundled: true
    description: null
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  jetbrains:
    available_tools: []
    bundled: true
    description: null
    display_name: Jetbrains
    enabled: false
    name: jetbrains
    timeout: 300
    type: builtin
  memory:
    available_tools: []
    bundled: true
    description: null
    display_name: Memory
    enabled: false
    name: memory
    timeout: 300
    type: builtin
  obsidian:
    args:
    - mcp-obsidian
    available_tools: []
    bundled: null
    cmd: uvx
    description: null
    enabled: false
    env_keys:
    - OBSIDIAN_API_KEY
    - OBSIDIAN_HOST
    envs: {}
    name: obsidian
    timeout: 300
    type: stdio
  playwright:
    args:
    - '@playwright/mcp'
    available_tools: []
    bundled: null
    cmd: npx
    description: null
    enabled: false
    env_keys: []
    envs: {}
    name: playwright
    timeout: 300
    type: stdio
  serena:
    args:
    - --from
    - git+https://github.com/oraios/serena
    - serena
    - start-mcp-server
    available_tools: []
    bundled: null
    cmd: uvx
    description: null
    enabled: false
    env_keys: []
    envs: {}
    name: serena
    timeout: 300
    type: stdio
  taskmaster:
    args:
    - -y
    - --package=task-master-ai
    - task-master-ai
    available_tools: []
    bundled: null
    cmd: npx
    description: null
    enabled: false
    env_keys:
    - ANTHROPIC_API_KEY
    envs: {}
    name: taskmaster
    timeout: 300
    type: stdio
  tutorial:
    available_tools: []
    bundled: true
    description: null
    display_name: Tutorial
    enabled: false
    name: tutorial
    timeout: 300
    type: builtin
GOOSE_PROVIDER: github_copilot
